### ISSUE TITLE
Add DOI for public release of v2.0.0

### ISSUE THREAD

**Issue by tallamjr** [LSSTDESC/snmachine#143]
Github and Zenodo have good integration for archiving a repo on a particular release such that one can have a DOI.

https://guides.github.com/activities/citable-code/

It would be nice to have something like this in the `README.md`:
![image](https://user-images.githubusercontent.com/8843728/58084682-40eac180-7bb3-11e9-8cff-9469282bc6ad.png)

**Comment by Catarina-Alves** [comment]
This is now implemented and shown in the README
