### ISSUE TITLE
make utils package a subpackage

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/snmachine#258]
As discussed on [desc-help](https://github.com/LSSTDESC/desc-help/issues/66#issuecomment-948611315), we are going to make `utils` a subpackage and update the pypi installation appropriately.

**Comment by heather999** [comment]
Dear @Catarina-Alves I'm sorry for the long delay - I have started to look at this again and will try to get back to you early next week!

**Comment by Catarina-Alves** [comment]
Hi @heather999, have you had some time to look at this? Thank you

**Comment by heather999** [comment]
Looking at it now!  I find part of the issue is that there is old code under `snmachine/utils/archive` which I believe is no longer relevant.  I am moving that `archive` directory aside and placing it back at the top-level of this repo.. then I am able to do a `editable` pip install using this copy of the code and run some of the example notebooks... with some minor modification now that `utils` is a subpackage of `snmachine`.    So I am modifying things to look like:
`from snmachine.utils.plasticc_pipeline import get_directories, load_dataset`
I recall you didn't need to do that when you tested against the original PR, but I still think that is necessary. I'll update the PR and we can both test this out again (and hopefully finally close this!)

**Comment by Catarina-Alves** [comment]
Solved by #259
