### ISSUE TITLE
request to remove sncosmo==2.1.0 constraint

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/snmachine#265]
Hi
We're including `snmachine` in the td_env (http://github.com/lsstdesc/td_env) and that has been working well while we were pinned to python 3.8 and an earlier version ot the LSST Sci Pipelines.  We're trying to upgrade and move to py 3.10.  The snmachine constraint on `sncosmo==2.1.0` https://github.com/LSSTDESC/snmachine/blob/abe55bac3154311477f108861274b3e453bc2285/setup.py#L68  is causing trouble.  sncosmo development has continued and more recent versions now support py 3.10, but I don't think this older sncosmo does.

Is this a true constraint for snmachine, and if so, what needs to be done to allow snmachine to use more recent versions of sncosmo?

**Comment by MichelleLochner** [comment]
Hi @heather999. Indeed I came across the same issue when doing some recent development and simply changed the requirement to >=2.1.0. sncosmo is only really included to support relic code, we don't use it much. I don't think changing the constraint will break anything important. Do you want me to do a quick hotfix on the main branch? Or will you just use a fork?
