### ISSUE TITLE
highly specific OpSimData reading structure

### ISSUE THREAD

**Issue by reneehlozek** [LSSTDESC/snmachine#30]
In sndata.py, the OpSim data structure is highly tuned (down to the LSST_Ia file names).
In general, it would be great to be able to pass a file root name and have the code read in the lightcurve (without assuming there is a Ia and a NONIa instance, and with an arbitrary filename). I modified sndata.py to do the latter, but there are lots of instances to the Ia and nonIa datasets separately, which fails if they don't exist.

Connected to that, the code

if isinstance(subset,basestring)and subset=='Ia':
            all_data=data_Ia
        elif isinstance(subset,basestring) and subset=='nIa':
            all_data=data_nIa
        else:
            all_data=data_Ia+data_nIa

comes too 'late', ie. it assumes you have the two separations in your data set.

**Comment by MichelleLochner** [comment]
I think the OpSim simulations has moved so far beyond this original file structure that this is probably irrelevant, beyond the desire to allow more general reading of datasets (which I think is a pipe dream at this point).
